# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 10:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0437\u0434\u0435\u043b\u0430')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u041e\u0431\u044a\u0435\u043a\u0442',
                'verbose_name_plural': '\u041e\u0431\u044a\u0435\u043a\u0442\u044b \u0434\u043b\u044f \u0440\u0430\u0437\u0434\u0435\u043b\u043e\u0432 \u0432 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u043e \u041a\u043e\u043c\u043f\u0430\u043d\u0438\u0438',
            },
        ),
    ]
