# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-11 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170711_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content_kg',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name_kg',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name_ru',
        ),
    ]
