# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-24 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170711_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
