# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_nakaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakaz',
            name='fio',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
